module.exports = val => {
    var result = [{ input: 'ก', output: 'k' },
    { input: 'ข', output: 'kh' },
    { input: 'ฃ', output: 'kh' },
    { input: 'ค', output: 'kh' },
    { input: 'ฅ', output: 'kh' },
    { input: 'ฆ', output: 'kh' },
    { input: 'ง', output: 'ng' },
    { input: 'จ', output: 'ch' },
    { input: 'ฉ', output: 'ch' },
    { input: 'ช', output: 'ch' },
    { input: 'ซ', output: 's' },
    { input: 'ฌ', output: 'ch' },
    { input: 'ญ', output: 'y' },
    { input: 'ฎ', output: 'd' },
    { input: 'ฏ', output: 't' },
    { input: 'ฐ', output: 'th' },
    { input: 'ฑ', output: 'th' },
    { input: 'ฒ', output: 'th' },
    { input: 'ณ', output: 'n' },
    { input: 'ด', output: 'd' },
    { input: 'ต', output: 't' },
    { input: 'ถ', output: 'th' },
    { input: 'ท', output: 'th' },
    { input: 'ธ', output: 'th' },
    { input: 'น', output: 'n' },
    { input: 'บ', output: 'b' },
    { input: 'ป', output: 'p' },
    { input: 'ผ', output: 'ph' },
    { input: 'ฝ', output: 'f' },
    { input: 'พ', output: 'ph' },
    { input: 'ฟ', output: 'f' },
    { input: 'ภ', output: 'ph' },
    { input: 'ม', output: 'm' },
    { input: 'ย', output: 'y' },
    { input: 'ร', output: 'r' },
    { input: 'ฤ', output: 'rue' },
    { input: 'ล', output: 'l' },
    { input: 'ฦ', output: 'lue' },
    { input: 'ว', output: 'w' },
    { input: 'ศ', output: 's' },
    { input: 'ษ', output: 's' },
    { input: 'ส', output: 's' },
    { input: 'ห', output: 'h' },
    { input: 'ฬ', output: 'l' },
    { input: 'อ', output: 'o' },
    { input: 'ฮ', output: 'h' }].find(t => t.input === val)
    if (result) {
        return result.output
    } else {
        return ''
    }
}